// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omjvpmydhboiqtzyxccp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tanZwbXlkaGJvaXF0enl4Y2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODk2MzksImV4cCI6MjA2MTM2NTYzOX0.1BmOzik8zPX-CF53mRoTbhrRWzs49Eb-zzdb7vE2RJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);